version: '3.7'
services:
  db:
    image: postgres
    env_file: .env
    container_name: 'database'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
